# Generated by Django 4.2.2 on 2023-08-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.CharField(max_length=20, unique=True)),
                ('jour', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.planning')),
            ],
        ),
    ]
