# Generated by Django 4.2.2 on 2023-09-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_planning_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planning',
            name='heure',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planning',
            name='jour',
            field=models.CharField(max_length=20),
        ),
    ]
